DNAProject/DNA

- README.md
Adjust the build icon place for easy recognize
> Adjust the build icon place

- common/common.go
- common/log/log.go
- consensus/dbft/consensusContext.go
- consensus/dbft/dbftService.go
- core/contract/contractContext.go
- core/ledger/block.go
- core/ledger/blockchain.go
- core/store/LevelDBStore/LevelDBStore.go
- core/validation/blockValidator.go
- net/httpjsonrpc/common.go
- net/httpjsonrpc/interfaces.go
- net/message/block.go
- net/message/consensus.go
- net/message/transaction.go
- net/node/node.go
- net/node/nodeMap.go
- net/node/transactionPool.go
- net/protocol/protocol.go
- vm/ECDsaCrypto.go
- vm/executionengine.go
> Clean up the print log info 

- common/log/log.go
- net/httpjsonrpc/interfaces.go
- net/httpjsonrpc/localServer.go
- nodectl.go
- utility/common.go
- utility/consensus/consensus.go
- utility/debug/debug.go
- utility/info/info.go
- utility/test/test.go
Set log debug level with command 'nodectl debug -level $NUM'
> Add subcommand 'nodectl debug'

- README.md
Add the project's Wiki and update the forum URL
> Add the correctly forum URL and Wiki URL

- config/config.go
- config/config.json
- core/ledger/block.go
- core/ledger/blockchain.go
- core/store/LevelDBStore/LevelDBStore.go
- main.go
- net/message/block.go
- net/message/inventory.go
- net/message/message.go
- net/message/verack.go
> block sync up feature

- net/httpjsonrpc/interfaces.go
The root cause is null pointer for Transaction Program, allocate memory before assign value to it
> Fix the nodectl can't show transactions issue

- core/transaction/payload/BookKeeping.go
- core/transaction/payload/IssueAsset.go
- core/transaction/payload/RegisterAsset.go
- core/transaction/payload/TransferAsset.go
- core/transaction/transaction.go
- net/httpjsonrpc/TransPayloadToHex.go
- net/httpjsonrpc/common.go
- net/httpjsonrpc/interfaces.go
1.format array []byte in payload of trans to hex string
2.Optimization of a single transaction converted to hexadecimal string
> Formatting trading the payload content for hexadecimal 

- README.md
Update the deployment way for both single-host and multi-hosts.
> Update deployment section in README

- consensus/dbft/dbftService.go
- core/store/LevelDBStore/LevelDBStore.go
- core/transaction/utxoTxInput.go
- core/validation/txValidator.go
1.changed to use Goroutine to verify the individual transaction.
2.changed to use map to check the utxo inputs.
As the test result now have about 1000 tps with validation process on single computer.
> Improved the validation Performance by Goroutine and map.

- core/ledger/ledgerStore.go
- core/store/LevelDBStore/DataEntryPrefix.go
- core/store/LevelDBStore/LevelDBStore.go
- core/transaction/txStore.go
- core/validation/txValidator.go
> save the quantityissued of the asset to db.

- core/store/LevelDBStore/LevelDBStore.go
- core/transaction/TransactionBuilder.go
- net/httpjsonrpc/interfaces.go
- net/httpjsonrpc/sampleTransaction.go
Bug fix with issue and transfer funcs.
There have problem with issue and transfer ,can't normal complete.
fixed the grpc tx generate and transaction building funcs.
changed to don't verify transactions when write out to db.
> Bug fix with issue and transfer funcs.

- .travis.yml
Remove the compile option using "go master".
> Remove the compile option using "go master".

- main.go
The c1-c4 miner won't create wallet.txt.
The miner named c will create wallet.txt for itself.
> The c1-c4 miner won't create wallet.txt

- core/store/LevelDBStore/LevelDBStore.go
- core/transaction/TransactionBuilder.go
- core/transaction/payload/Record.go
- core/transaction/transaction.go
- net/httpjsonrpc/interfaces.go
- net/httpjsonrpc/sampleTransaction.go
add the feature of record transaction. Add grpc test func.
> implement of transaction payload of Record.

- net/message/verack.go
- net/node/infoUpdate.go
- net/node/nodeMap.go
- net/protocol/protocol.go
Check local header height whether lower than other nodes
every 3 seconds. If so, send getheaders req to sync
up headers.
> Move getheaders req to update info feature

- net/httpjsonrpc/RPCserver.go
- net/httpjsonrpc/TransPayloadToHex.go
- net/httpjsonrpc/common.go
- net/httpjsonrpc/interfaces.go
- utility/common.go
- utility/info/info.go
1 update  getrawtransaction sendrawtransaction  rpc-api  interface
2 record transaction of block  by rpc-api call
> add getrawtransaction sendrawtransaction test function

- consensus/dbft/dbftService.go
- core/validation/blockValidator.go
- core/validation/txValidator.go
- main.go
- net/message/transaction.go
- net/node/link.go
- net/node/transactionPool.go
Move the transaction verification from consensus to txpool
Add a function to verify duplicate UTXO inputs in txpool
> Do transaction verification before joining in txpool

- core/ledger/blockchain.go
- core/ledger/ledger.go
- core/ledger/ledgerStore.go
- core/store/LevelDBStore/LevelDBStore.go
- core/validation/txValidator.go
1. read last block hash/height.
2. read last header hash/height.
3. read every header hash to header_index array.
> read last blockchain data in db when initialize leveldbstore.

- common/common.go
- core/ledger/ledgerStore.go
- core/store/LevelDBStore/LevelDBStore.go
- net/message/block.go
- net/message/blockHdr.go
- net/message/consensus.go
- net/message/inventory.go
- net/message/message.go
- net/message/notfound.go
- net/message/verack.go
- net/node/infoUpdate.go
- net/node/node.go
- net/protocol/protocol.go
1. change getdata request handle process 
2. move consensus message handle from message.go to consensus.go
> change getdata request handle process 

- README.md
Remove the Chinese characters from the default readme file
the CN version will be created in another file
> Change the default readme to pure English

- core/contract/program/ProgramBuilder.go
- core/contract/program/ProgramBuilder_test.go
bug fixed of OpCode set when -1
compare with the ScriptBuilder.cs of Antshares.
it should be PUSHM1.
> bug fixed of OpCode set when -1

- core/transaction/TransactionBuilder.go
BugFix of unset of input/output utxo when transfer.
have test with full test (reg/issue/transfer)
> BugFix of unset of input/output utxo when transfer.

- README.md
- config/config.go
- config/config.json
- consensus/dbft/consensusContext.go
- consensus/dbft/dbftService.go
- consensus/dbft/prepareRequest.go
- core/ledger/block.go
- core/ledger/blockchain.go
- core/ledger/blockdata.go
- core/ledger/ledger.go
- core/store/LevelDBStore/LevelDBStore.go
- core/validation/blockValidator.go
- core/validation/txValidator.go
- docs/specifications/data.md
- main.go
- net/httpjsonrpc/common.go
- net/httpjsonrpc/interfaces.go
- net/message/consensus.go
- net/message/version.go
- net/net.go
- net/node/node.go
- net/protocol/protocol.go
change miner to bookKeeper to avoid missunderstanding like BTC mining.
> change miner to bookKeeper

- config/config.go
- consensus/dbft/consensusContext.go
- consensus/dbft/dbftService.go
- main.go
- net/message/message.go
- net/message/ping.go
- net/message/pong.go
- net/message/verack.go
- net/node/infoUpdate.go
- net/node/node.go
- net/protocol/protocol.go
> nextminer feature

- client/account.go
- client/client.go
- common/uint160.go
Signed-off-by: zhengq1 ljqlyy@gmail.com
> fix address generate from programhash not from publickeyhash

- net/message/ping.go
- net/message/pong.go
- net/node/node.go
- net/protocol/protocol.go
Add local block height in ping/pong message
for block synchronization and header synchronization
> Add height in ping/pong message

- cli/wallet/wallet.go
- net/httpjsonrpc/common.go
- net/httpjsonrpc/interfaces.go
- net/httpjsonrpc/sampleTransaction.go
Minor fixes for following:
1.	show public key and address while listing wallet info
2.	will not broadcast transaction when verification failed
> show wallet public key and don't broadcast invalid transaction

- main.go
- net/node/infoUpdate.go
- net/node/node.go
- net/protocol/protocol.go
solve service node sync up block issue and consensus should wait for at least 4 peers issue
> solve service node sync up block issue and consensus should wait for at least 4 peers issue

- cli/cli.go
- common/config/config.go
- crypto/crypto.go
- crypto/sm2/sm2.go
- crypto/sm3/sm3.go
- crypto/sm3/sm3_test.go
- crypto/sm3/sm3block.go
- crypto/util/util.go
- main.go
- net/node/link.go
1.Add SM3 algorithm
2.Make SM3 as default algorithm in SM2
Signed-off-by: XiaoJie Guo <guoxiaojie@onchain.com>
> Add SM3 algorithm

- config.json
- main.go
- net/node/node.go
The log message printed at the main function can't be recorded
by the log system, clean up them and set the default log level
to 1 which mean the Debug message will not be print by default
> Clean up log message the main function

- account/account.go
- account/account_test.go
- account/client.go
- account/fileStore.go
- account/store.go
- cli/asset/asset.go
- cli/common/common.go
- cli/wallet/wallet.go
- common/common.go
- common/config/config.go
- config.json
- consensus/dbft/consensusContext.go
- consensus/dbft/dbftService.go
- core/ledger/blockchain.go
- crypto/helper.go
- main.go
- net/httpjsonrpc/interfaces.go
- net/httpjsonrpc/sampleTransaction.go
- net/message/address.go
- net/message/consensus.go
- net/message/transaction.go
- net/message/verack.go
- net/message/version.go
- net/net.go
- net/node/link.go
- net/node/node.go
- net/protocol/protocol.go
Geneated the bookkeeper nodes' ID(public key by seed node have the
private key leaking issue) correct it via be geneated by the node
itself. and the publickey should be set at the config file now
Code clean up of the client module
The bookKeepers node could be generated as below:
1: Run nodectl wallet -c
2: Run nodectl wallet -l to get the publickey
3: Copy the public key to the config.json BookKeepers field, 4 of
different publickeys are needed at least
TODO: Get the wallet password from the inputting by user
> Generate the wallet by the node itself instead by the seed node.

- events/eventType.go
- net/node/eventNotice.go
- net/node/infoUpdate.go
- net/node/link.go
- net/node/node.go
If rx function detects that the node is disconnected,
set the node state is inactivity.
> If the node is disconnected change node state

- cli/cli.go
- cli/privpayload/privpayload.go
- core/store/ChainStore/ChainStore.go
- core/transaction/TransactionBuilder.go
- core/transaction/payload/PrivacyPayload.go
- core/transaction/transaction.go
- glide.lock
- glide.yaml
- net/httpjsonrpc/TransPayloadToHex.go
Add an New type payload into DNA. This payload can contain raw data or
the payload of other type. User can use a nodectl's command "ppayload"
to get a privacy payload.
Signed-off-by: d5c5ceb0 <d5c5ceb0@gmail.com>
> Add privacy payload into DNA

- common/config/config.go
- common/log/log.go
- main.go
- net/node/infoUpdate.go
add limit one log size feature
> add limit one log size feature

- .gitignore
- cli/privpayload/privpayload.go
- core/ledger/block.go
- core/ledger/blockdata.go
- core/signature/signature.go
- core/transaction/payload/PrivacyPayload.go
- core/transaction/transaction.go
- core/validation/validation.go
- net/message/consensus.go
- nodectl.go
- test/asset.sh
- test/testPrivPayload.sh
Add a test case for testing privacypayload. To use this test case,
You should copy the nodectl and config.json to the same folder as
this testPrivPayload.sh. Then run testPrivaPayload on a shell after
the DNA servers setting up.
Signed-off-by: zhangwei <d5c5ceb0@gmail.com>
> add privacypayload test case

- net/httprestful/common/common.go
- net/httprestful/restful/server.go
1.Must add form param of raw=1
> New restful protocol of response block and tx raw data

- consensus/dbft/dbftService.go
- core/validation/blockValidator.go
- core/validation/txValidator.go
- net/httpjsonrpc/common.go
- net/message/transaction.go
- net/net.go
- net/node/transactionPool.go
- net/protocol/protocol.go
Reconstruction of TxnPool
1.package transaction pool.
all transaction should flow into txnpool first, when txnpool's
validation passed, it will add into the process transaction scope.
2.implement of transaction pool validation.
Flowchart:https://www.processon.com/view/link/5939550be4b05a4d43805ffc
Tests:
I have test with 20W reg transaction has about 150s in my own computer.
(before fix is about 140s)and have test with
reg->issue->transfer->record all seems ok.
> Reconstruction of TxnPool.

- net/httprestful/common/common.go
1.avoid resp["Raw"] is nil or other type error
> Avoid resp["Raw"] is nil or other type error

- account/client.go
- glide.lock
- glide.yaml
Getting updates from golang.org website is very slow, use github
link instead.
> Fix the glide configration file

- core/transaction/utxoTxInput.go
> transaction input index should serialize()/deserialize() with Uint16.

- common/serialization/serialize.go
- core/account/accountstate.go
- core/ledger/ledgerStore.go
- core/store/ChainStore/ChainStore.go
- core/store/ChainStore/DataEntryPrefix.go
based on the input and output to calculate the balance of each account assets.
> add account balance support

- core/transaction/transaction.go
- core/validation/txValidator.go
1.add error return when deserialize failed.
2.add invalide payload check.
> add error return when deserialize failed.

- cli/data/data.go
- core/store/ChainStore/ChainStore.go
- core/transaction/TransactionBuilder.go
- core/transaction/payload/DataFile.go
- core/transaction/transaction.go
- core/validation/txValidator.go
- glide.lock
- glide.yaml
- net/httpjsonrpc/RPCserver.go
- net/httpjsonrpc/TransPayloadToHex.go
- net/httpjsonrpc/interfaces.go
- net/httpjsonrpc/ipfsclusterAPI.go
- net/httpjsonrpc/ipfsclusterAPI_test.go
- net/httpjsonrpc/rpcResult.go
- nodectl.go
1.add IPFS/cluster api support
2.add new payload type:DataFile
3.create new cli cmd to access IPFS API
> Initial API for IPFS &IPFS-Cluster support

- net/message/blockHdr.go
We doesn't need reverse the buffer when use it.
Change the serialization and deserilazation to serialize
and deserialize the message member one by one.
> Fix block header sync up issue

- core/transaction/transaction.go
> change TransferAsset TransactionType value equal to Antshares.

- core/transaction/transaction.go
> make the same value of TransferAsset transaction type as antshares.

- core/store/ChainStore/ChainStore.go
the inconsistence was caused by failed to call function 'ChainStore.go:persist',
and function 'ChainStore.go:persistBlocks' ignored to handle the error,
made BlockHeight updated but ChainStore.currentBlockHeight unchanged,
So will create wrong consensusContext  in consensusContext.go:Reset function
> fix inconsistent currentBlockHeight and preHash in consensusContext Reset function

- core/transaction/txAttribute.go
After the transaction nonce be moved to attribute, the
serialization/deserialization of Nonce type are missing.
> Bug fix for missing nonce attribute serialization

- README.md
- README_CN.md
Update README.md and README_CN.md
Signed-off-by: XiaoJie Guo <guoxiaojie@onchain.com>
> Update README.md and README_CN.md

- account/client.go
- cli/wallet/wallet.go
1. Add functions to support change password
2. Provide command line to change wallet password
nodectl wallet --changepassword
need to input old password then double confirm new password.
> Add change wallet password function

- core/store/ChainStore/ChainStore.go
- net/node/infoUpdate.go
- net/node/node.go
- net/protocol/protocol.go
> sync block feature update

- net/message/message.go
- net/node/infoUpdate.go
- net/node/link.go
- net/protocol/protocol.go
1. Add magic header search: make sure we would not miss the msg hdr under poor network or high throughput  environment.
2.Add handshake to reduce unnecessary connection.
3.Reduce the RX buffer to reduce memory used in network connection.
> Improve the memory usage and network connection  

- core/store/ChainStore/ChainStore.go
Signed-off-by: wangbing <wangbing@onchain.com>
> Fix utxo double spend check failure bug

- core/transaction/transaction.go
- core/validation/txValidator.go
1.implement of transaction asset precision check.
2.add transaction precision check when regtransaction.
3.when balance check add Value check and IssueAsset exception.
4.fixed a little bug of transactionResult's variable init problem.
> Fixed some bug of txValidator

- core/ledger/ledgerStore.go
- core/store/ChainStore/ChainStore.go
- core/validation/txValidator.go
When verify transaction, must check if transaction hash duplicated.
> duplicate transaction check

- cli/asset/asset.go
- core/asset/asset.go
- core/validation/txValidator.go
- net/httpjsonrpc/sampleTransaction.go
fixed testcase error of precision
> fixed testcase error of precision

- net/message/block.go
- net/message/blockHdr.go
- net/message/inventory.go
when get header, there is no need to get block detail.
> optimize blockHeader get.

- net/message/version.go
- net/node/link.go
- net/protocol/protocol.go
Add a handshake timer, if the node doesn't receive
version and verack message from a peer in 10 seconds,
remove the peer from connecting list.
> Add a handshake timer

- core/ledger/ledgerStore.go
- core/store/ChainStore/ChainStore.go
- core/store/ChainStore/DataEntryPrefix.go
- core/transaction/utxoUnspent.go
> getunspent UTXO for every address / asset

- net/message/message.go
> Handle the not found msg

- net/message/message.go
- net/message/notfound.go
> More fix for not found msg

- net/node/infoUpdate.go
- net/node/link.go
- net/node/node.go
- net/protocol/protocol.go
1. rm legacy node when reconnect
2. add back off time when reconnect
3. Create a new routine to check network connection
> Optimize the connect code

- core/ledger/ledgerStore.go
- core/store/ChainStore/ChainStore.go
1. get unspents UTXO info for every asset by a programhash.
2. get every asset info.
> get every unspents UTXO info / get every asset info

- consensus/dbft/dbftService.go
- core/ledger/blockchain.go
- core/store/ChainStore/ChainStore.go
- net/message/block.go
Some error prints aren't errors use warning instead.
Some warning prints aren't warnings use infomation instead.
> change print level

- consensus/dbft/consensusContext.go
- consensus/dbft/consensusState.go
- consensus/dbft/dbftService.go
- core/ledger/blockchain.go
- net/message/block.go
- net/message/inventory.go
An too early broadcast of block hash causes leveldb not found error
> broadcast block hash after block's persist complete

- consensus/dbft/dbftService.go
- core/ledger/block.go
- core/transaction/payload/BookKeeping.go
- core/transaction/transaction.go
as BookKeeping transaction upgraded,
set BookKeepingVersion from 0x02 -> 0x03.
> upgrade BookKeeping payload version

- common/config/config.go
- consensus/dbft/dbftService.go
- net/net.go
- net/node/transactionPool.go
add a option of  limit of max transaction in block.
> add a option of limit of max transaction in block.

- common/uint160.go
- net/httprestful/common/common.go
- net/httprestful/common/custom.go
- net/httprestful/restful/server.go
1.get balance by addr and asset
2.get utxo by addr
3 get contract
4.change send record response result
> Add new restful protocol

- account/client.go
- core/ledger/block.go
- core/ledger/blockchain.go
- core/store/ChainStore/ChainStore.go
- main.go
Check bookkeeper count when start up;
Optimize  passing argument in GenesisBlockInit()
Change some log error to Fatal
Check genesis block exist in chain or not
TODO: add genesis block check when sync block
> Add validation of bookkeepers.

- main.go
- net/message/block.go
- net/node/node.go
- net/protocol/protocol.go
Add a chan to check if the sync up block with other nodes
finished. Start consensus after it.
> start consensus after finish block syncup

- cli/asset/asset.go
- core/asset/asset.go
- net/httpjsonrpc/sampleTransaction.go
> add description attribute of asset.

- net/message/blockHdr.go
If input <=0, Intn(input) would panic and app crash
> Fix Intn() panic issue

- consensus/dbft/dbftService.go
> guarantee the ExpectedView number not less than ViewNumber + 1

- net/node/transactionPool.go
cause values in inputUTXOList of txpool are all nil
> fix variable shadowing: inputUTXOList in txpool

- common/log/log.go
> Add date in log

- consensus/dbft/dbftService.go
- core/validation/blockValidator.go
- core/validation/txValidator.go
- errors/errcode.go
- net/httpjsonrpc/common.go
- net/httpjsonrpc/interfaces.go
- net/httprestful/common/common.go
- net/httprestful/common/custom.go
- net/httprestful/error/error.go
- net/message/transaction.go
- net/net.go
- net/node/transactionPool.go
- net/protocol/protocol.go
> Add transaction verify errcode

- net/node/link.go
> If node state is INACTIVITY, return Tx directly

- net/message/inventory.go
> Avoiding the duplicated block request under consensus state

- net/httprestful/common/common.go
- net/httprestful/restful/server.go
- net/httpwebsocket/server.go
1.restful Get Total Issued by assetid
2.restful Get Block Transactions hash by height
3.websocket push block bytes
4.websocket push Block Transactions hash
> Add push block txs hash  in restful  and websocket protocol

- core/store/ChainStore/ChainStore.go
- core/store/ChainStore/DataEntryPrefix.go
the header do not need to persist in db before receive a full block
> remove the header persist in db

- net/message/blockHdr.go
> Remove logic which increase node sync header load.

- net/node/infoUpdate.go
The heartbeat timeout value should associate with period update
interval.
> change heartbeat timeout value
