- core/ledger/block.go
- core/ledger/blockchain.go
- core/ledger/ledgerStore.go
- core/store/LevelDBStore/LevelDBStore.go
- core/validation/blockValidator.go
- net/message/blockHdr.go
when headers sync to local, save headers to leveldb in batch.
when blocks sync to local, save it in cache first, then persist block to leveldb while height of blocks is in order at cache.
> leveldbstore modify AddHeaders() & persistBlocks()

- vm/func_crypto.go
1.When get signature list from vm stack, should use the signature list length for the loop. (there is a mistake in previous code). 
2.Verify the signature failure doesn't need to return verify fail, it is unnecessary verify all successful.
> Fix vm verify multi signature bug

- consensus/dbft/dbftService.go
- core/validation/blockValidator.go
- core/validation/txValidator.go
Some performance issue fix.
<dbftService.go>
1.When in BlockSent status, should not changeView, just need to wait the block persistent complete.
<blockValidator.go>
1.append has a large performance loss,so changed to only 2 append process.
2.should not return when  VerifySignableData ok, otherwise it will skip the transaction verify.
<txValidator.go>
1.With no UTXOInputs could return it immediately. otherwise, it will run len([]*tx.Transaction) times.
Signed-off-by: luodanwg<luodan.wg@gmail.com>
> Some performance issue fix.

- core/ledger/header.go
- net/message/block.go
- net/message/inventory.go
Add cnt in invPayload to record the hash count, so that the
serialize doesn't need to calculate the length and save it
in front of the serialized hash. Also the deserialize doesn't
need to judge the length itself.
> Change the inv message content

- consensus/dbft/dbftService.go
- core/validation/blockValidator.go
- net/net.go
- net/node/transactionPool.go
- net/protocol/protocol.go
make TXNPool to clear after blockPersistent.
solved the transaction missing issue.
Changed TxnPool to clean after block persist completed.
Delete more than 4000 transactions spend about 20-30ms in 
normal PC testing 
> solve the transaction missing issue.

- common/log/log.go
- core/validation/txValidator.go
- main.go
- net/httpjsonrpc/common.go
- net/httpjsonrpc/interfaces.go
- net/httpjsonrpc/sampleTransaction.go
- utility/common.go
- utility/test/test.go
1. Fix client name typo
2. Support setting the log level to 'maxprintlevel'
3. Move the sample transaction to node side, nodectl supports two ways to send tx: 
a) performance testing transactions
b) register/issue/transfer transactions
4. Workaround UTXO inputs verification issue since it stops generating block 
5. Remove the unnecessary input http.Request parameter
> bug fixes for nodectl, httpjson, and tx

- net/message/blockHdr.go
- net/message/message.go
- net/message/verack.go
- net/node/node.go
- net/node/nodeMap.go
- net/protocol/protocol.go
Send getheaders message when the local block height is less
than others and receive verack message.
If the other node block height is more than 2000, send
getheaders request again after receive blkheader from other
node and verify the previous headers are valid.
If the previous headers are invalid, send getheaders request
to another node.
Send getblock message until the block headers finish sync up.
> change getheaders message logic

- core/ledger/block.go
Fixed the bug of block SerializeUnsigned.
The block SerializeUnsigned is still in blank, so the block signBySigner
func is sign a nil data now.
Have tested with 10W transactions with no error.
Signed-off-by: junjie <luodan.wg@gmail.com>
> Fixed the bug of block SerializeUnsigned.

- core/store/LevelDBStore/LevelDBStore.go
- core/transaction/TransactionResult.go
- core/transaction/transaction.go
- core/validation/txValidator.go
- net/httpjsonrpc/interfaces.go
fixed the transactionResult issue.
1.As the transactionResult func can't process with duplicate
input assetID utxo and duplicate output assetID utxo.
so divided into input result and output result func to calc
the amout group by assetid first.
2.add transfer I/O balance check.
* have test with 10w transactions and full process(reg->issue->transfer)
> fixed the transactionResult issue.

- core/validation/txValidator.go
if IsDoubleSpend, the func return true not false.
> fix the judgement of return value in VerifyTransactionWithLedger() func

- client/account.go
- config/config.go
- config/config.json
- core/store/LevelDBStore/LevelDBStore.go
- main.go
User can config the miner count at the beginning of
starting the system by setting MinerCount in
config.json.
eg. If MinerCount is 5, the minername for four peers
should be c1, c2, c3, c4, c5.
> User can config the miner count at the beginning

- consensus/dbft/dbftService.go
- core/ledger/ledger.go
- core/ledger/ledgerStore.go
- core/store/LevelDBStore/LevelDBStore.go
- main.go
- net/message/block.go
- net/message/consensus.go
- net/message/inventory.go
- net/message/message.go
- net/net.go
- net/node/node.go
- net/protocol/protocol.go
1.  Remove the needless signature checking when receive
prepare request message，the checking will only be done 
after received prepare response message.
2.   Broadcast inv message rather than full block.  Each peer constructs
and saves block by itself then send inv message to other peers.
> Broadcast INV message rather than full block

- net/node/link.go
Currently the node's status is set as inactivity when the connection
channle read error happend, it is not neccessary as the period update
function will send ping/pong message to check this and update the
node's status
> Set the node inactive status at the period update process

- net/httpjsonrpc/RPCserver.go
- net/httpjsonrpc/TransPayloadToHex.go
- net/httpjsonrpc/common.go
- net/httpjsonrpc/interfaces.go
- net/httpjsonrpc/rpcResult.go
- utility/common.go
- utility/test/test.go
1. Found bugs when use third-pary tool access RPC interface, fix them and
optimize RPC server. Now id is not an input parameter for registered
functions. Makes these interfaces more friendly, we can use tool which
support JSON to interact with Chain!
2. Remove -nosign flag when sending sample transaction with nodectl
since we always verify it on chain.
3. Add error messages and catching for RPC server, users could get 
more detailed information when they do some ops on chain.
> bug fixes and code optimizing for RPC interfaces

- consensus/dbft/consensusContext.go
- consensus/dbft/consensusMessage.go
- consensus/dbft/dbftService.go
- consensus/dbft/prepareRequest.go
- core/transaction/txAttribute.go
- main.go
- net/httpjsonrpc/sampleTransaction.go
- net/node/transactionPool.go
Sent all entire transactions got from transaction pool other than
transaction hashes in Prepare Request. The first transaction in block 
still be bookkeeping transaction. If non-primary nodes receive
transactions which doesn't exist in local transaction pool then 
do fully transaction verification.
> Sent entire transaction other than transaction hash in Prepare Request

- consensus/dbft/dbftService.go
The generate block time should at least twice as long as
node info update interval.
> change genblock time 6

- vm/utils/stack.go
- vm/utils/stack_test.go
got confirmed with the maintainer of vm.
bug fixed the issue of the RandomAccessStack struct function: Insert .
cause of override data shared by two array slice.
> fix: override data shared by two array slice in vm\utils\stack.go

- Makefile
- cli/cli.go
- cli/info/info.go
- common/config/config.go
- main.go
- net/httpjsonrpc/RPCserver.go
- net/httpjsonrpc/interfaces.go
1. Add an --nodeversion(-v) option for `nodectl info` subcommand
2. Add a RPC interface `getversion`
Using command line
$ nodectl info --nodeversion (-v)
to show connected remote node version
> Get connected remote node version by using nodectl

- consensus/dbft/dbftService.go
Check the GenBlockTime in config.json. If it is less than 6,
print warning message and set it to be 6.
> Limit GenBlockTime must longer than 6 seconds

- client/account_test.go
- client/client.go
- common/log/log.go
- common/log/log_test.go
1. Fix the out of range bug in client/client.go:SaveAccount when the length of private key is less than 32 bytes(the leading byte(s) is 0).
2. Check the pointer "Log" before used in Info, Warn, Error and Fatal.
> Fix bugs in client.go and log.go

- net/node/infoUpdate.go
- net/node/node.go
- net/protocol/protocol.go
flightHeight array in each peer node may be filled with outdated requests forever.
So before send Block Request message, remove request whose height is less than current BlockHeight in each peer node's flightHeight array.
> fix SyncBlk issue

- core/transaction/transaction.go
- core/transaction/txAttribute.go
- net/httpjsonrpc/common.go
- net/httpjsonrpc/interfaces.go
When receive a transaction which has attribute, the transaction can't be
written on chain. The cause is that transaction serialization failed
when do verification. Fix this bug and remove unused transaction
description type.
> Fix transaction attribute serialization bug

- net/node/infoUpdate.go
- net/node/link.go
- net/node/node.go
some method declaration in node struct use object type instead of pointer type.
which lead to several different local node instances and TxPool objects shared the same TxPool list.
cause concurrent access TxPool list and program crash
> fix bug: concurrent access TxPool list

- cli/test/test.go
- consensus/dbft/consensusContext.go
- consensus/dbft/dbftService.go
- core/ledger/blockchain.go
- core/ledger/ledgerStore.go
- core/store/ChainStore/ChainStore.go
- core/store/ChainStore/DataEntryPrefix.go
- core/transaction/TransactionBuilder.go
- core/transaction/payload/BookKeeper.go
- core/transaction/transaction.go
- core/validation/txValidator.go
- main.go
- net/httpjsonrpc/TransPayloadToHex.go
- net/httpjsonrpc/interfaces.go
this pull add  support for dynamic bookkeeper list configuration.
1. add a new bookkeeper transaction payload 
2. expose it to httpjsonrpc interface and "nodectl test" sub-command for test purpose
3. change the bookkeeper logic in consensus module
4. add bookkeeper transaction and bookkeeper list logic in ledger store
Usage of "nodectl test" :
remove node 3 from the bookkeeper list:
first copy node3‘s wallet.dat file to the node which nodectl connects to, and rename it to wallet3.dat,
then:
```bash
nodectl test -t bookkeeper -a sub -n 3
```
add node 4 into the bookkeeper list:
first copy node4‘s wallet.dat file to the node which nodectl connects to, and rename it to wallet4.dat,
then:
```bash
nodectl test -t bookkeeper -a add -n 4
```
> support for dynamic bookkeeper list configuration

- crypto/sm2/sm2.go
Before SM2 signing and verifying, combine the signed message with user
id, curve parameters and public key, as described in SM2 specification.
> Fix SM2 signature to follow the specification

- cli/asset/asset.go
- cli/privpayload/privpayload.go
- consensus/dbft/dbftService.go
- core/ledger/block.go
- core/transaction/transaction.go
- core/transaction/txAttribute.go
- net/httpjsonrpc/common.go
- net/httpjsonrpc/interfaces.go
In order to be consistent with antshare's transaction serialization.
when with no balance, there is need to serialize nonce. just skip it
when serialization
> transaction balance serialization

- common/log/log.go
Windows system cann't use colon naming files or folders,
so use dot instead of colon naming the log.
> use dot instead of colon naming the log

- core/transaction/transaction.go
- core/transaction/txAttribute.go
- core/validation/blockValidator.go
when err is nil, function NewDetailErr returns nil.
so when called in the case the function will eat the error.
cause confusing result and misleading execution flow.
>  fix the  misuse of NewDetailErr function

- net/message/blockHdr.go
currently this function's intention is :
1) startHash == empty, stopHash == empty: return headers in range [1, min(2000, curHeight)];
2) startHash == empty, stopHash != empty: return headers in range [hstop, hstop + min(2000, curHeight)]
3) startHash != empty, stopHash == empty: return headers in range [0, min(2000, hstart)]
4) startHash != empty, stopHash != empty: return headers in range [max(hstop, hstart - 2000), hstart]
the implementation code have two issues:
in condition 2 : when curHeight > 2000, return headers in range [hstop, hstop + 2000],
which may cause error in the following for loop if curHeight < hstop + 2000
in condition 4: if hstart - hstop > 2000, return headers in range [hstart+ 2000, hstart + 4000],
also will cause error.
> fix logic error in GetHeadersFromHash function

- account/client.go
- cli/asset/asset.go
- cli/common/common.go
- cli/data/data.go
- cli/privpayload/privpayload.go
- cli/wallet/wallet.go
- common/password/password.go
- net/httpjsonrpc/interfaces.go
1. Any operations based on wallet always need to input wallet password,
no default password now.
2. Provide -p option for node program to specify wallet password.
3. When using wallet from command line, provide two ways to input
walle password:
a) specify with -p,--password <password string>
b) when -p, --password is omitted, prompt user to input password
4. Wallet creation needs double confirmed password input when no
-p,--password is specified. If wallet already exists then program exits.
TODO: move sample transaction Bookkeeper to nodectl as a subcommand
> Remove default wallet password

- cli/cli.go
- common/log/log.go
- main.go
Changed log initialization function as following:
1. log.Init()
No log output will be printed. All outputs will be redirected to
/dev/null. nodectl will use this for disabling log function.
2. log.Init("./Log")
log will be saved to ./Log dirctory.
3. log.Init("./Log", stdout)
log will be saved to ./Log dirctory and printed to stdout.
> bug fix for blank log files

- common/log/log.go
The root cause is logfile is initialized incorrectly and LOG module don`t have valid *os.file 
> Fix the log issue: cannot stat log file size

- net/node/link.go
Or node will unable to connect another since the last dial failed
> Remove addr from connecting list when dial failed

- common/log/log.go
- net/message/message.go
- net/node/link.go
1. remove Mutex since method in std log package can be called simultaneously
2. log level check first to avoid unnecessary execution
3. provide Debugf, Infof, Warnf ... method to delay the execution of fmt.Sprintf.
4. remove some costly debug call in node/link.go, message.go
> optimize log package

- common/serialization/serialize.go
- common/serialization/serialize_test.go
benchmark data:
```bash
go test -test.bench=".*" -benchmem
```
after optimize:
```
BenchmarkWriteVarUint-4         50000000                26.9 ns/op            16 B/op          1 allocs/op
BenchmarkWriteVarBytes-4        30000000                49.9 ns/op            25 B/op          1 allocs/op
BenchmarkWriteVarString-4       20000000                74.3 ns/op            37 B/op          2 allocs/op
BenchmarkReadVarUint-4          20000000                75.9 ns/op            64 B/op          2 allocs/op
BenchmarkReadVarBytes-4         20000000               105 ns/op              80 B/op          3 allocs/op
BenchmarkReadVarString-4        10000000               147 ns/op              96 B/op          4 allocs/op
BenchmarkSerialize-4             2000000               764 ns/op …
```
> optimize serialization functions

- core/store/LevelDBStore/LevelDBStore.go
a key existence benchmark test shows that it has 25~30% speed up and almost equal memory consumption .
testcase:  first pre-allocate 200000 keys and put into leveldb, then take 400000 key existence test.
> add bloom filter option to speed up key existence test

- net/node/link.go
- net/node/node.go
- net/protocol/protocol.go
the addr existence test and add operation is not done in one atomic step,
which causes duplicated items in connectinglist，and multiple connecting .
> fix concurrency problem in connnectinglist cause of api design

- core/ledger/ledger.go
- core/ledger/ledgerStore.go
- core/store/ChainStore/ChainStore.go
Is more efficient use IsBlockInStore() instead of GetBlock().
> Determine if block (with hash) is stored in db

- core/store/ChainStore/ChainStore.go
currently, the blockCache is used to hold blocks which has not been persisted, once the block persist is complete, it will be deleted from the blockCache, So add a  persisted block into the blockCache, it will not be removed forever, cause memory leak.
> fix blockCache memory leak

- consensus/dbft/dbftService.go
- core/ledger/block.go
- core/transaction/payload/BookKeeping.go
- core/transaction/transaction.go
- net/httpjsonrpc/TransPayloadToHex.go
as now BookKeeping with no nonce, so all the bookKeeping transaction
are the same hash and will overwrite the old bookKeeping transaction.
the genesisblock would be
{
"Action": "getblockbyheight",
"Desc": "SUCCESS",
"Error": 0,
"Result": {
"Hash": "db40a76edf7035b3f2c307f0dd3e08f52b70a98dc8bee3089bfe7cbd80f0e7f6",
"BlockData": {
"Version": 0,
"PrevBlockHash": "0000000000000000000000000000000000000000000000000000000000000000",
"TransactionsRoot": "fb5bd72b2d6792d75dc2f1084ffa9e9f70ca85543c717a6b13d9959b452a57d6",
"Timestamp": 1487808000,
"Height": 0,
"ConsensusData": 2083236893,
"NextBookKeeper": "d02be7dd4f1f3dac60576ab00d8753b9151ed8c3",
"Program": {
"Code": "",
"Parameter": "51"
},
"Hash": "db40a76edf7035b3f2c307f0dd3e08f52b70a98dc8bee3089bfe7cbd80f0e7f6"
},
"Transactions": [
{ …
> add nonce to BookKeeping transaction

- core/store/ChainStore/ChainStore.go
- net/node/link.go
1. delete useless break
2. add node id prints when io.EOF exception happens.
3. change one warning to debug, since most of the time
it is just a sign of end of cache.
> some code optimization

- core/ledger/blockchain.go
- core/ledger/ledgerStore.go
- core/store/ChainStore/ChainStore.go
- main.go
redesign the chainstore block processing logic with multi-read, single write model
the original design of chainstore holds RWLock  too long, even a single call of GetHeaderHeight method may be blocked > 10s,
so ping message can not be constructed immediately;  SyncHeader, SyncBlk function will be blocked. and the timer in node.updateNodeInfo function will be delayed severely. causes keep-alive timeout and node reconnecting.
> fix keep-alive timeout: redesign the chainstore block processing logic

- core/transaction/payload/BookKeeper.go
- core/transaction/payload/BookKeeping.go
- core/transaction/payload/DataFile.go
- core/transaction/payload/DeployCode.go
- core/transaction/payload/IssueAsset.go
- core/transaction/payload/PrivacyPayload.go
- core/transaction/payload/Record.go
- core/transaction/payload/RegisterAsset.go
- core/transaction/payload/TransferAsset.go
- core/transaction/transaction.go
Pass the version to payload, and payload can decide how to deserialize by version.
I have tested it on test environment. you also can check it by :
http://42.159.228.69:60334/api/v1/block/details/height/45221
http://42.159.228.69:60334/api/v1/block/details/height/45222
45221 block is the old payload version which have no nonce.
45221 block is the new payload version which have  nonce.
by version code, it can be deserialized according to type intelligence.
And keep the data compatible.
> add version control of payload.

- core/transaction/transaction.go
bug: GetTransactionResults() will return assets only occured in output.
pass the version to payload, and payload can decide how to Deserialize.
> fixed GetTransactionResults bug.

- net/node/infoUpdate.go
1.when neighbor height lower than local, skip it
2.Ping node periodically.
> Avoiding sync with lower height node

- net/message/blockHdr.go
- net/node/infoUpdate.go
- net/node/node.go
- net/protocol/protocol.go
Sync fail flag lead to no hdr request issue when network poor, so remove it
Request hdr from a random select node
> Remove sync fail flag and fetch block header from neighbor node randomly

- consensus/dbft/consensusContext.go
- consensus/dbft/dbftService.go
the header is used as cache to reduce the computation of MerkleTree.
when change context , the header should also be cleared
> fix header inconsist with context

- core/validation/validation.go
- crypto/crypto.go
- crypto/p256r1/p256r1.go
- crypto/sm2/sm2.go
- vm/ECDsaCrypto.go
1.Reduce the return value of crypto.Verify() from 2 to 1 so that the
result can be easily to judged. if return value "error" is nil
verifysignature successed, otherwise failed.
Signed-off-by: XiaoJie Guo <guoxiaojie@onchain.com>
> Fix crypto.Verify issue.

- net/message/blockHdr.go
integer underflow when a node's curBlockHeight less than stopHeight, 
which is the case if this node fell behind others.
> fix: integer underflow

- core/store/ChainStore/ChainStore.go
if an header have been checked and added in headerCache,
an block with right hash but wrong signatures may skip check and persist to db.
> fix: signatures in block header may skip check

- net/message/blockHdr.go
- net/node/infoUpdate.go
- net/node/node.go
- net/protocol/protocol.go
The root cause is the new header sync logic not check the height of remote node.
So if node be acquired a higher block the error info print.
> Fix the “GetBlockWithHeight failed” error

- net/protocol/protocol.go
The synchronized node would running into unstable state under heave sync request
> Change the max header count when sync with others, reduce the node load

- common/config/config.go
- net/message/blockHdr.go
- net/node/node.go
- net/protocol/protocol.go
Too many concurrent handle of sync header would lower the node`s performance.
> Limit the concurrent sync header responses
